### PR TITLE
Use `inherits` for smaller bundle sise

### PR DESCRIPTION
**Pull request by feross**
This saves 3.5KB (after minify+gzip!) in the webtorrent bundle!

### CODE REVIEW

**Comment by ralphtheninja** [comment]
:+1:

**Comment by mafintosh** [comment]
@feross is there no browserify transform for this?

**Comment by mafintosh** [comment]
2.0.1

**Comment by feross** [comment]
No, but perhaps browserify should do the same for this as it currently does for `Buffer.isBuffer`.

**Comment by feross** [comment]
When browserify sees `Buffer.isBuffer`, it uses the implementation from [is-buffer](https://www.npmjs.com/package/is-buffer) instead of including the whole `buffer` package.

**Comment by feross** [comment]
@mafintosh Opened an issue on browserify for this: https://github.com/substack/node-browserify/issues/1503

**Pull request merged**
