### PR TITLE
Fixes #13

### LINKED ISSUE #13: stream.stream() does not advance the stream
According to the docs, calling `stream.stream()` should advance the stream so that the `box` event fires again if there are more boxes. This does not happen.

Below is the code I would expect to work, but it only ever emits the first box. I've validated that the stream returned from `stream.stream()` does emit an `end` event, so that's not the issue. Also, it does call the `_kick` function, but the problem is that `_pending` isn't `0`. I just can't figure out why - could be an off-by-one error.

``` js
var fs = require('fs')
var mp4 = require('mp4-stream')

var stream = mp4.decode()

stream.on('box', function (headers) {
  console.log(headers.type)
  stream.stream().resume()
})

fs.createReadStream('./test.m4v').pipe(stream)
```

### PR DESCRIPTION
**Pull request by nklhrstv**
Fixes  #13 receiving of `box` events once `decode.stream` is called.

### CODE REVIEW

**Comment by mafintosh** [comment]
Want me to add you as a maintainer? Don't have a lot of time to maintain this atm.

**Comment by mafintosh** [comment]
Could you make an independent test for this? A bit tricky to see what this fixes, so an individual failing test that is fixed by this PR would be good

**Comment by nklhrstv** [comment]
@mafintosh ive added another test just for this bug

**Comment by nklhrstv** [comment]
Now its ready for a review

**Comment by nklhrstv** [comment]
@mafintosh Hi did you manage to check this PR? i really need this...

**Comment by mafintosh** [comment]
Thanks for the test. Releasing

**Comment by mafintosh** [comment]
3.1.3

**Pull request merged**
